### ISSUE TITLE
ORIG_EAX not defined?

### ISSUE THREAD

**Issue by liuyanghejerry** [Hexcles/Eevee#3]
It seems ORIG_EAX is not defined and cannot compile caretaker.c which needs ORIG_EAX at line 316 in syscall_listener.c included by caretaker.c.

**Comment by Hexcles** [comment]
@lx75249 Have a look!

**Comment by conopt** [comment]
- \- 看来还得弄个configure.. 等我撑过了一大波期中考试就搞

**Comment by conopt** [comment]
@liuyanghejerry 你是x64系统么？Linux or BSD？发行版？

**Comment by liuyanghejerry** [comment]
Centos 6.3 x64

**Comment by fanzeyi** [comment]
看来就是 x64 的问题了，把那个 hotfix PR 过来吧 :beer:

**Comment by mingc00** [comment]
Chang from ’4 \* ORIG_EAX’ to ’8 \* ORIG_RAX’
reference: http://www.theantway.com/2013/01/12/notes-for-playing-with-ptrace-on-64-bits-ubuntu-12-10/

**Comment by fanzeyi** [comment]
#4 fixed this, closed.

:beer:
